---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# Dengue epidemiology in Vientiane prefecture, Lao PDR

<!-- badges: start -->
<!-- badges: end -->

## Context

This is the Lao package of the [Ecomore 2](http://www.ecomore.org) project,
focused on the epidemiology of dengue in the province of Vientiane prefecture,
Lao PDR. The project is funded by the
[Agence Française de Développement](https://afd.fr) and run by the
[Institut Pasteur du Laos](http://www.pasteur.la), in collaboration with the
[Institut de Recherche pour le Développement](https://en.ird.fr) and the
[Centre National de la Recherche Scientifique](http://www.cnrs.fr).

**Contact:** please contact Dr. Marc Grandadam (PI, <m.grandadam@pasteur.la>)
for any question regarding the project and its data.

**Bug report and feature request**: you can report bugs or inconsistencies or 
request for additional feature by clicking `New issue` 
[here](https://github.com/ecomore2/ecomore2.github.io/issues).

## Data sets

* [IPL](http://www.pasteur.la)'s epidemiological data (2012-present): [CSV](https://raw.githubusercontent.com/ecomore2/pacs/master/data/pacs.csv) (1.2 MB), [description](https://ecomore2.github.io/pacs)
* [IPL](http://www.pasteur.la)'s GPS data (2012-present): [CSV](https://raw.githubusercontent.com/ecomore2/gps/master/data/gps.csv) (66 KB), [description](https://ecomore2.github.io/gps)
* [LBS](https://www.lsb.gov.la)'s census data (2015): [CSV](https://raw.githubusercontent.com/ecomore2/census/master/data/census.csv) (1.9 MB), [description](https://ecomore2.github.io/census)
* [LBS](https://www.lsb.gov.la)'s villages polygons (2015): [description](https://ecomore2.github.io/villages-polygons)
* [TuTiempo.net](https://en.tutiempo.net)'s daily meteorological data (4 stations, 2010-present): [description](https://ecomore2.github.io/meteo)
   + [meteo.csv](https://raw.githubusercontent.com/ecomore2/meteo/master/data/meteo.csv) (905 KB)
   + [stations.csv](https://raw.githubusercontent.com/ecomore2/meteo/master/data/stations.csv) (211 B, [EPSG](http://www.epsg.org):[4326](https://epsg.io/4326) projection in decimal degrees)
* [ESA](https://www.esa.int)'s
  [GlobCover](http://due.esrin.esa.int/page_globcover.php)'s land cover data (300-m resolution, [EPSG](http://www.epsg.org):[4326](https://epsg.io/4326) projection in decimal degrees): 
  [description](https://ecomore2.github.io/globcover)
   + 2005: [GlobCover2005_V2.2.tif](https://www.dropbox.com/s/gp790fng3awwb7t/Globcover2005_V2.2.tif?raw=1) (37 Ko)
   + 2009: [GlobCover2009_V2.3.tif](https://www.dropbox.com/s/d2fdtq8jofs38tf/Globcover2009_V2.3.tif?raw=1) (38 Ko)
* [EU](https://ec.europa.eu/jrc/en)'s
  [GHSL](https://ghsl.jrc.ec.europa.eu)'s built-up data (38-m resolution, [EPSG](http://www.epsg.org):[3857](https://epsg.io/3857) projection in decimal degrees): [description](https://ecomore2.github.io/ghsl)
   + 1990: [builtup1990res38m3857.tif](https://www.dropbox.com/s/4sxdsmj0s2nxy5c/builtup1990res38m3857.tif?raw=1) (1 MB)
   + 2000: [builtup2000res38m3857.tif](https://www.dropbox.com/s/en0u787brvk75pe/builtup2000res38m3857.tif?raw=1) (1 MB)
   + 2014: [builtup2014res38m3857.tif](https://www.dropbox.com/s/0jxx754zudgldf2/builtup2014res38m3857.tif?raw=1) (1 MB)
* [WorldPop](https://www.worldpop.org)'s population and urbanisation data (90-m resolution, [EPSG](http://www.epsg.org):[4326](https://epsg.io/4326) projection in decimal degrees): [description](https://ecomore2.github.io/worldpop)
   + [Population](https://www.worldpop.org/geodata/summary?id=61) data (2010, 2015):
      - [VT_popmap10_admin001.tif](https://www.dropbox.com/s/b1byouuilije6ly/VT_popmap10_admin001.tif?raw=1) (2.1 MB)
      - [VT_popmap10adj_admin001.tif](https://www.dropbox.com/s/9ottfpf34oznywx/VT_popmap10adj_admin001.tif?raw=1) (2.1 MB)
      - [VT_popmap15_admin001.tif](https://www.dropbox.com/s/kc8rq5mh6tq2sxk/VT_popmap15_admin001.tif?raw=1) (2.1 MB)
      - [VT_popmap15adj_admin001.tif](https://www.dropbox.com/s/snthubnbx2i4en5/VT_popmap15adj_admin001.tif?raw=1) (2.1 MB)
   + [Urban change](https://www.worldpop.org/geodata/summary?id=1228) data (2000, 2010):
      - [VT00urbchg.tif](https://www.dropbox.com/s/wdl4mqvod5w0x2t/VT00urbchg.tif?raw=1) (342 KB)
      - [VT10urbchg.tif](https://www.dropbox.com/s/n8hqh2vs6b72fmi/VT10urbchg.tif?raw=1) (343 KB)

## R packages

* [ecomore](https://ecomore2.github.io/ecomore): code used in the project.
* [rama](https://r-and-gama.github.io/rama): an R interface to the Agend-Based
Modeling platform [GAMA](https://gama-platform.github.io).

## Studies

* [Spatio-temporal dynamics of dengue incidence](https://ecomore2.github.io/spatio-temporal-description)